---
- name: Initialize CA server
  hosts: vpn_server
  become: true
  become_user: root
  vars_prompt:
    - name: remote_username
      prompt: Enter a username
      private: no
  vars:
    source_dir: ~/.ssh
    remote_path: "/home/{{remote_username}}/.ssh"
    user: "{{remote_username}}"
  tasks:
