---
- name: Initialize CA server
  hosts: vpn_server
  become: true
  become_user: "{{remote_username}}"
  vars_prompt:
    - name: remote_username
      prompt: Enter username...
      private: no
  tasks:
    # TODO: generate keys so that I can SCP files between VPN & CA servers
    - name: Generate key
      command: >
        sh -c "ssh-keygen"
