---
- name: Initialize VPN Server Step 1
  hosts: vpn_server
  become: true
  become_user: "{{remote_username}}"
  vars_prompt:
    - name: remote_username
      prompt: Enter username...
      private: no
  tasks:
    - name: Cleanup old easy-rsa dir and files
      shell: "rm -rf /home/{{remote_username}}/easy-rsa /home/{{remote_username}}/easy-rsa/pki/reqs/server.req /home/{{remote_username}}/easy-rsa/pki/private/server.key"
      become: true
      become_user: root
    - name: Install OpenVPN and easy-rsa
      become: true
      become_user: root
      apt:
        name:
          - openvpn
          - easy-rsa
        state: present
    - name: Create easy-rsa directory
      file:
        path: "/home/{{remote_username}}/easy-rsa"
        state: directory
        mode: "0777"
        force: yes
    - name: Create symlink to easy-rsa
      command: >
        sh -c "ln -s /usr/share/easy-rsa/* /home/{{remote_username}}/easy-rsa/"
    - name: Init easy-rsa
      command: >
        sh -c "cd /home/{{remote_username}}/easy-rsa && ./easyrsa init-pki"
    - name: Copy vars to remote
      become: true
      become_user: root
      copy:
        content: "{{ lookup('file', './vars.vpn.txt') }}"
        dest: "/home/{{remote_username}}/easy-rsa/pki/vars"
        force: no
        backup: yes
    - name: Build OpenVPN CA
      expect:
        command: ./easyrsa gen-req server nopass
        chdir: "/home/{{remote_username}}/easy-rsa"
        responses:
          "Common Name": 'server\n'
          "Enter pass phrase": '\n'
          "Confirm pass phrase": '\n'
    - name: Copy server.req to local
      fetch:
        src: "/home/{{remote_username}}/easy-rsa/pki/reqs/server.req"
        dest: "./reqs/"
        flat: yes
        validate_checksum: yes
        mode: "0644"
